"""Protocol interfaces for service dependencies.

Services depend on these protocols, not concrete adapter implementations.
This keeps the dependency direction clean: adapters implement protocols,
services consume them.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol


class SteamConfigAdapter(Protocol):
    """Protocol for Steam configuration operations."""

    def grid_dir(self) -> str | None: ...
    def read_shortcuts(self) -> dict: ...
    def write_shortcuts(self, data: dict) -> None: ...
    def set_steam_input_config(self, app_ids: list, mode: str = "default") -> None: ...
    def write_shortcut_icon(self, app_id: int, icon_bytes: bytes) -> str: ...
    def check_retroarch_input_driver(self) -> dict | None: ...
    def fix_retroarch_input_driver(self) -> dict: ...


class RommApiProtocol(Protocol):
    """Domain-oriented interface for all RomM server operations.

    Replaces raw HTTP path construction in services with semantic methods.
    Concrete implementation: ``adapters.romm.romm_api.RommApiAdapter``.
    Requires RomM >= 4.8.1.
    """

    def set_version(self, version: str | None) -> None:
        """Store the detected RomM server version string.

        Passing ``None`` clears the cached version (used when the server
        becomes unreachable and the cached version should no longer be
        trusted).
        """
        ...

    def get_version(self) -> str | None:
        """Return the detected RomM server version string, or ``None`` if unset."""
        ...

    def heartbeat(self) -> dict:
        """Check server connectivity and retrieve version info.

        Returns the raw heartbeat response dict from /api/heartbeat.
        """
        ...

    def list_platforms(self) -> list[dict]:
        """Fetch all platforms configured on the RomM server.

        Returns a list of platform dicts from /api/platforms.
        """
        ...

    def list_collections(self) -> list[dict]:
        """Fetch all user-created collections from the RomM server."""
        ...

    def list_virtual_collections(self, collection_type: str) -> list[dict]:
        """Fetch virtual (autogenerated) collections of a given type (e.g., 'franchise')."""
        ...

    def get_current_user(self) -> dict:
        """Fetch the currently authenticated user profile.

        Returns user dict from /api/users/me.
        """
        ...

    def get_rom(self, rom_id: int) -> dict:
        """Fetch a single ROM by ID.

        Returns the ROM dict from /api/roms/{rom_id}.
        """
        ...

    def list_roms(self, platform_id: int, limit: int = 50, offset: int = 0) -> dict:
        """List ROMs for a platform with pagination.

        Returns paginated response {"items": [...], "total": N}
        from /api/roms filtered by platform_ids.
        """
        ...

    def list_roms_updated_after(
        self,
        platform_id: int,
        updated_after: str,
        limit: int = 1,
        offset: int = 0,
    ) -> dict:
        """List ROMs updated after a given timestamp.

        Used for incremental sync to detect changes since last sync.
        Returns paginated response filtered by updated_after parameter.
        """
        ...

    def download_rom_content(
        self,
        rom_id: int,
        filename: str,
        dest: str,
        progress_callback: Any = None,
    ) -> None:
        """Download a ROM file to a local destination.

        Streams /api/roms/{rom_id}/content/{filename} to dest.
        Filename is URL-encoded. Optional progress_callback for tracking.
        """
        ...

    def download_cover(self, cover_url: str, dest: str) -> None:
        """Download a ROM cover image to a local path.

        cover_url is the relative path from the RomM server.
        Spaces in the URL are encoded before downloading.
        """
        ...

    def list_firmware(self) -> list[dict]:
        """Fetch all available firmware/BIOS files from the server.

        Returns a list of firmware dicts from /api/firmware.
        """
        ...

    def get_firmware(self, firmware_id: int) -> dict:
        """Fetch metadata for a single firmware file.

        Returns firmware dict from /api/firmware/{firmware_id}.
        """
        ...

    def download_firmware(self, firmware_id: int, filename: str, dest: str) -> None:
        """Download a firmware/BIOS file to a local path.

        Streams /api/firmware/{firmware_id}/content/{filename} to dest.
        """
        ...

    def list_saves(
        self,
        rom_id: int,
        *,
        device_id: str | None = None,
        slot: str | None = None,
    ) -> list[dict]:
        """List saves for a ROM.

        Pass device_id to populate device_syncs in response,
        and slot to filter by save slot.
        """
        ...

    def upload_save(
        self,
        rom_id: int,
        file_path: str,
        emulator: str,
        save_id: int | None = None,
        *,
        device_id: str | None = None,
        slot: str | None = None,
        overwrite: bool = False,
    ) -> dict:
        """Upload or update a save file.

        Pass device_id for sync tracking, slot for slot assignment,
        and overwrite=True to force-upload over conflicts.
        Raises RommConflictError on 409 when overwrite=False and conflict detected.
        """
        ...

    def download_save_content(
        self,
        save_id: int,
        dest_path: str,
        *,
        device_id: str | None = None,
        optimistic: bool = True,
    ) -> None:
        """Download save content with optional device sync tracking.

        When device_id is set, optimistic=True auto-marks device as synced;
        optimistic=False requires a manual confirm_download() call.
        """
        ...

    def confirm_download(self, save_id: int, device_id: str) -> dict:
        """Manually confirm a save download for device sync tracking.

        Only needed when download_save_content() was called with optimistic=False.
        """
        ...

    def get_save_summary(self, rom_id: int, device_id: str | None = None) -> dict:
        """Fetch grouped save summary for a ROM with slot breakdown.

        Uses /api/saves/summary — returns structured response grouped by slot.
        Pass device_id to include device sync status per save.
        """
        ...

    def download_save(self, save_id: int, dest_path: str) -> None:
        """Download a save file to a local path.

        Downloads directly via /api/saves/{save_id}/content.
        """
        ...

    def get_save_metadata(self, save_id: int) -> dict:
        """Fetch metadata for a single save.

        Returns save dict from /api/saves/{save_id}.
        """
        ...

    def get_rom_with_notes(self, rom_id: int) -> dict:
        """Fetch full ROM detail including user notes.

        Used for playtime tracking. Notes are in the all_user_notes field.
        """
        ...

    def create_note(self, rom_id: int, data: dict) -> dict:
        """Create a note on a ROM.

        Used for playtime tracking. POST /api/roms/{rom_id}/notes.
        """
        ...

    def update_note(self, rom_id: int, note_id: int, data: dict) -> dict:
        """Update an existing note on a ROM.

        PUT /api/roms/{rom_id}/notes/{note_id}.
        """
        ...

    def list_roms_by_collection(self, collection_id: int, limit: int = 50, offset: int = 0) -> dict:
        """List ROMs belonging to a user-created collection with pagination.

        Returns paginated response {"items": [...], "total": N}
        from /api/roms filtered by collection_id.
        """
        ...

    def list_roms_by_virtual_collection(self, virtual_id: str, limit: int = 50, offset: int = 0) -> dict:
        """List ROMs belonging to a virtual (autogenerated) collection with pagination.

        Returns paginated response {"items": [...], "total": N}
        from /api/roms filtered by virtual_collection_id.
        """
        ...

    def delete_server_saves(self, save_ids: list[int]) -> dict:
        """Delete saves from the RomM server by ID.

        Endpoint: POST /api/saves/delete with body {"saves": [id1, id2, ...]}.
        """
        ...

    def register_device(self, name: str, platform: str, client: str, client_version: str) -> dict:
        """Register this client as a sync device on the RomM server.

        Returns device dict with id, name, created_at.
        """
        ...

    def list_devices(self) -> list[dict]:
        """List all devices registered with the RomM server for the current user.

        Returns a list of device dicts from /api/devices.
        """
        ...

    def update_device(self, device_id: str, **fields) -> dict:
        """Update a registered device's metadata on the RomM server.

        Currently the plugin only sends ``client_version`` via the reconciliation
        loop; the server accepts additional fields per its OpenAPI schema (name,
        platform, client, ip_address, mac_address, hostname, sync_enabled) but
        they are not exercised by this plugin.
        """
        ...


# ---------------------------------------------------------------------------
# Time, identity, and async-sleep Protocols
# ---------------------------------------------------------------------------


class Clock(Protocol):
    """Sole source of wall-clock and monotonic time for services.

    Services must obtain timestamps through a Clock so deterministic tests
    can pin time without monkey-patching ``time`` or ``datetime``. Concrete
    implementations belong in adapters (``adapters.system_clock``); fakes
    live in ``tests.fakes.system_time``.
    """

    def now(self) -> datetime:
        """Return the current UTC-aware wall-clock instant."""
        ...

    def monotonic(self) -> float:
        """Return a monotonic clock reading in seconds.

        Suitable for measuring elapsed durations; not comparable to ``time``.
        """
        ...

    def time(self) -> float:
        """Return the current Unix timestamp in seconds since the epoch."""
        ...


class UuidGen(Protocol):
    """Sole source of UUID values for services.

    Services consume this Protocol instead of ``uuid.uuid4`` directly so
    tests can supply deterministic IDs.
    """

    def uuid4(self) -> str:
        """Return a new random UUID4 in canonical string form (e.g. ``"a1b2…"``)."""
        ...


class Sleeper(Protocol):
    """Sole async-sleep seam for services.

    Services await ``sleeper.sleep(seconds)`` instead of ``asyncio.sleep``
    so tests can collapse delays and assert on requested durations.
    """

    async def sleep(self, seconds: float) -> None:
        """Suspend the current coroutine for ``seconds`` seconds."""
        ...


# ---------------------------------------------------------------------------
# Infrastructure callback Protocols
# ---------------------------------------------------------------------------


class StatePersister(Protocol):
    """Persist plugin state to disk (zero-argument callable)."""

    def __call__(self) -> None: ...


class SettingsPersister(Protocol):
    """Persist settings to disk (zero-argument callable)."""

    def __call__(self) -> None: ...


class PendingSyncReader(Protocol):
    """Read seam for the LibraryService pending-sync map.

    SteamGridService consults the pending-sync map when resolving SGDB
    IDs for ROMs that are mid-sync (not yet in the registry). Exposing
    this as a Protocol avoids a service-to-service concrete import and
    keeps the typed seam narrow to "give me the current mapping".
    """

    def __call__(self) -> dict: ...


class DownloadQueueCleanup(Protocol):
    """Eviction seam for the in-memory ROM download queue.

    Consumed by ``RomRemovalService`` to remove queue entries when a ROM
    is deleted. Exposing this as a Protocol avoids a service-to-service
    concrete import and keeps the typed seam narrow to "evict one entry"
    and "clear all entries".
    """

    def evict(self, rom_id: int) -> None: ...

    def clear(self) -> None: ...


class SaveSyncStatePersister(Protocol):
    """Read/write the on-disk save-sync state file.

    Implementations are responsible for atomic writes, locking, and
    handling missing/corrupt files. They perform dumb I/O only —
    schema migrations on loaded data live in ``StateService``, so
    ``load`` returns the raw dict (or ``None`` when the file does not
    yet exist) without versioning the payload.
    """

    def save(self, data: dict) -> None: ...

    def load(self) -> dict | None: ...


class FirmwareCachePersister(Protocol):
    """Read/write the on-disk firmware list cache.

    Owns the round-trip for the cached firmware listing consumed by
    ``FirmwareService``. Path, file format, and version handling are
    adapter concerns — services see only the dict payload they
    previously wrote. ``load`` returns an empty dict (not ``None``)
    when no cached payload is available so callers can probe with
    ``"items" in data`` without a None-check.
    """

    def save(self, data: dict) -> None: ...

    def load(self) -> dict: ...


class EventEmitter(Protocol):
    """Emit named events with a data payload to the frontend."""

    async def __call__(self, event: str, /, *args: object) -> None: ...


class DebugLogger(Protocol):
    """Log a debug/trace message string."""

    def __call__(self, msg: str) -> None: ...


class SystemResolver(Protocol):
    """Resolve a RomM platform slug to a RetroDECK system path."""

    def __call__(self, platform_slug: str, platform_fs_slug: str | None = None) -> str: ...


class SavesPathProvider(Protocol):
    """Return the current RetroDECK saves directory path."""

    def __call__(self) -> str: ...


class RomsPathProvider(Protocol):
    """Return the current RetroDECK roms directory path."""

    def __call__(self) -> str: ...


class BiosPathProvider(Protocol):
    """Return the current RetroDECK BIOS directory path."""

    def __call__(self) -> str: ...


class RetroDeckHomeProvider(Protocol):
    """Return the current RetroDECK home directory path."""

    def __call__(self) -> str: ...


class RetroArchSaveSortingProvider(Protocol):
    """Return RetroArch save sorting settings as (sort_by_content, sort_by_core)."""

    def __call__(self) -> tuple[bool, bool]: ...


class CoreResolverFn(Protocol):
    """Resolve the active RetroArch core for a system/game."""

    def __call__(self, system_name: str, rom_filename: str | None = None) -> tuple[str | None, str | None]: ...


class CoreInfoProvider(Protocol):
    """Core resolution for ES-DE configured systems, consumed by services.

    Exposes the read seam services need to ask "which RetroArch core is
    active for this system/ROM?" without depending on the concrete
    adapter. Implementations own the underlying file reads and may
    cache parse results; ``reset_cache`` lets writers invalidate the
    cache after editing the underlying configuration.
    """

    def get_active_core(
        self,
        system_name: str,
        rom_filename: str | None = None,
    ) -> tuple[str | None, str | None]: ...

    def get_available_cores(self, system_name: str) -> list[dict]: ...

    def reset_cache(self) -> None: ...


class GamelistXmlEditorProtocol(Protocol):
    """Write seam for ES-DE per-system / per-game core overrides.

    Lets ``main.py`` callables mutate ``gamelist.xml`` without
    depending on the concrete adapter. Reads remain a
    ``CoreInfoProvider`` concern.
    """

    def set_system_override(
        self,
        retrodeck_home: str,
        system_name: str,
        core_label: str | None,
    ) -> bool: ...

    def set_game_override(
        self,
        retrodeck_home: str,
        system_name: str,
        rom_path: str,
        core_label: str | None,
    ) -> bool: ...


class CoreNameProviderFn(Protocol):
    """Return the RetroArch canonical ``corename`` for a core shared object.

    Implemented by :class:`adapters.retroarch_core_info.RetroArchCoreInfoAdapter`.
    ``core_so`` is the full ``.so`` basename including the ``_libretro``
    suffix (e.g. ``"snes9x_libretro"``). Returns ``None`` when the ``.info``
    file is missing or lacks a ``corename`` field — callers must fail loud,
    not fall back to ES-DE labels.
    """

    def __call__(self, core_so: str) -> str | None: ...


class ArtworkRemover(Protocol):
    """Delete the on-disk artwork files associated with a registry entry.

    Consumed by ``ShortcutRemovalService`` to clean up grid/banner/cover
    files when a shortcut is removed. The exact set of files and the
    naming scheme are an artwork-layer concern — this Protocol exposes
    only the single-entry deletion seam the removal flow needs.
    """

    def remove_artwork_files(self, grid: str, rom_id: str | int, entry: dict) -> None: ...


class PathExistsProbe(Protocol):
    """Generic filesystem existence probe.

    Used by services that need to check whether a path is currently
    present on disk without touching ``os.path`` directly. Distinct from
    the domain-shaped ``CoverArtFileStore`` / ``DownloadFileAdapter`` /
    ``MigrationFileAdapter`` Protocols: this one exposes only the
    semantic question "does this path exist?" and carries no implication
    about which subtree of the filesystem the caller is reasoning about.
    """

    def exists(self, path: str) -> bool:
        """Return True when *path* refers to an existing file or directory."""
        ...


class CoverArtFileStore(Protocol):
    """Filesystem seam for cover-art file operations.

    Owns the raw POSIX calls (``exists``, ``remove``, atomic ``rename``,
    ``listdir``, ``isdir``, ``read_bytes``) ArtworkService uses to manage
    cover art under the Steam grid directory. Path construction, registry
    lookups, and orphan detection remain a service concern; this Protocol
    exposes only the I/O seams.

    Implementations are synchronous — services that call from an async
    context offload via ``loop.run_in_executor``.
    """

    def exists(self, path: str) -> bool:
        """Return True when *path* refers to an existing file or directory."""
        ...

    def remove(self, path: str) -> None:
        """Delete *path*. Idempotent: a missing file is not an error."""
        ...

    def rename(self, src: str, dst: str) -> None:
        """Atomically rename *src* to *dst*, replacing any existing file at *dst*."""
        ...

    def listdir(self, directory: str) -> list[str]:
        """Return the entries in *directory*."""
        ...

    def isdir(self, path: str) -> bool:
        """Return True when *path* exists and is a directory."""
        ...

    def read_bytes(self, path: str) -> bytes:
        """Return the contents of *path* as raw bytes."""
        ...


class DownloadFileAdapter(Protocol):
    """Filesystem seam for ROM download target operations.

    Owns the raw POSIX calls DownloadService uses to manage downloaded
    ROM files: temp-file lifecycle, atomic renames, disk-space probes,
    ZIP extraction with ZIP-slip protection, post-extract URL-decoding,
    and file-size scans for launch-file detection. Path construction,
    queue management, and progress callbacks remain a service concern;
    this Protocol exposes only the I/O seams.

    Implementations are synchronous — services that call from an async
    context offload via ``loop.run_in_executor``.
    """

    def exists(self, path: str) -> bool:
        """Return True when *path* refers to an existing file or directory."""
        ...

    def remove(self, path: str) -> None:
        """Delete *path*. Idempotent: a missing file is not an error."""
        ...

    def remove_tree(self, path: str) -> None:
        """Recursively delete *path*. Idempotent: a missing directory is not an error."""
        ...

    def make_dirs(self, path: str) -> None:
        """Create *path* and any missing parents. Idempotent."""
        ...

    def rename(self, src: str, dst: str) -> None:
        """Atomically rename *src* to *dst*, replacing any existing file at *dst*."""
        ...

    def disk_free(self, path: str) -> int:
        """Return the free space in bytes for the filesystem hosting *path*."""
        ...

    def walk_files_matching_suffixes(self, base_dir: str, suffixes: tuple[str, ...]) -> list[str]:
        """Recursively list files under *base_dir* whose name ends with any of *suffixes*.

        Returns absolute paths. Idempotent on missing *base_dir*
        (returns ``[]``). Pure listing — does not mutate the filesystem;
        callers own the removal loop and any per-file error handling.
        """
        ...

    def extract_zip(self, archive_path: str, dest_dir: str, safe_root: str) -> None:
        """Extract *archive_path* into *dest_dir* with ZIP-slip protection.

        *safe_root* is the boundary outside of which extraction is
        rejected. Implementations resolve both *dest_dir* and *safe_root*
        via ``os.path.realpath`` and verify that every member resolves
        within *safe_root* before extracting.
        """
        ...

    def decode_url_encoded_names(self, directory: str) -> None:
        """Recursively rename URL-encoded entries under *directory*.

        Files and subdirectories whose names contain ``%XX`` escapes are
        renamed in place to their decoded form. Walks bottom-up so
        nested encoded directories are handled correctly.
        """
        ...

    def scan_files_with_sizes(self, directory: str) -> list[tuple[str, int]]:
        """Recursively list files under *directory* with their sizes.

        Returns a list of ``(absolute_path, size_bytes)`` tuples. Files
        whose size cannot be read report size ``0`` so callers can still
        reason over the list.
        """
        ...

    def write_text_atomic(self, path: str, content: str) -> None:
        """Atomically write *content* to *path* as UTF-8 text.

        Writes to a temp file beside *path* and ``os.replace``s it to
        the final destination. The temp file is removed on any failure.
        """
        ...


class DownloadQueueAdapter(Protocol):
    """Filesystem seam for the launcher-script download request queue.

    Owns the lock-and-poll round-trip DownloadService uses to consume
    queued ROM-download requests written by the RetroDECK launcher
    script. Path construction and request dispatch remain a service
    concern; this Protocol exposes only the read-and-clear seam.

    Implementations are synchronous — services that call from an async
    context offload via ``loop.run_in_executor``.
    """

    def poll_and_clear(self, path: str) -> list[dict]:
        """Atomically read all pending requests from *path* and clear the file.

        Acquires an exclusive ``fcntl`` lock for the read-and-truncate
        round-trip so concurrent writers cannot lose requests. Returns
        the list of request dicts that were in the file. Idempotent on
        missing or malformed files: returns ``[]``.
        """
        ...


class FirmwareFileAdapter(Protocol):
    """Filesystem seam for firmware/BIOS file operations.

    Owns the raw POSIX calls FirmwareService uses to manage firmware
    downloads under the RetroDECK BIOS directory: existence probes,
    atomic temp-file lifecycle, parent-directory creation, MD5 hashing
    of downloaded payloads, and BIOS registry JSON reads. Path
    construction, registry lookups, and download orchestration remain a
    service concern; this Protocol exposes only the I/O seams.

    Implementations are synchronous — services that call from an async
    context offload via ``loop.run_in_executor``.
    """

    def exists(self, path: str) -> bool:
        """Return True when *path* refers to an existing file or directory."""
        ...

    def remove(self, path: str) -> None:
        """Delete *path*. Idempotent: a missing file is not an error."""
        ...

    def rename(self, src: str, dst: str) -> None:
        """Atomically rename *src* to *dst*, replacing any existing file at *dst*."""
        ...

    def make_dirs(self, path: str) -> None:
        """Create *path* and any missing parents. Idempotent."""
        ...

    def checksum_md5(self, path: str) -> str:
        """Return the hex-encoded MD5 digest of *path*'s contents."""
        ...

    def read_bytes(self, path: str) -> bytes:
        """Return the contents of *path* as raw bytes."""
        ...


class MigrationFileAdapter(Protocol):
    """Filesystem seam for RetroDECK path and save-sort migration I/O.

    Owns the raw POSIX calls MigrationService uses to walk source
    locations, create destination directories, and relocate files when
    the RetroDECK home path changes or RetroArch save sorting flips.
    Path construction, conflict policy, and state updates remain a
    service concern; this Protocol exposes only the I/O seams.

    The Protocol distinguishes ``move`` from ``rename`` because the two
    migration flows have different filesystem semantics. ``move`` is
    the cross-device-safe shutil-style relocation used for RetroDECK
    home changes (e.g., internal SSD to SD card); it falls back to
    copy+delete on ``EXDEV``. ``rename`` is the same-filesystem atomic
    ``os.replace`` used inside the saves tree where source and
    destination are guaranteed to share a filesystem.

    Implementations are synchronous — services that call from an async
    context offload via ``loop.run_in_executor``.
    """

    def exists(self, path: str) -> bool:
        """Return True when *path* refers to an existing file or directory."""
        ...

    def is_dir(self, path: str) -> bool:
        """Return True when *path* exists and is a directory."""
        ...

    def make_dirs(self, path: str) -> None:
        """Create *path* and any missing parents. Idempotent."""
        ...

    def remove(self, path: str) -> None:
        """Delete the file at *path*. Idempotent: a missing file is not an error."""
        ...

    def remove_tree(self, path: str) -> None:
        """Recursively delete *path*. Idempotent: a missing directory is not an error."""
        ...

    def move(self, src: str, dst: str) -> None:
        """Cross-filesystem-safe move from *src* to *dst*.

        Uses ``shutil.move`` semantics: a same-filesystem rename when
        possible, falling back to copy+delete on ``EXDEV``. Use this
        for RetroDECK home migrations where source and destination may
        live on different filesystems.
        """
        ...

    def rename(self, src: str, dst: str) -> None:
        """Atomically rename *src* to *dst*, replacing any existing file at *dst*.

        Uses ``os.replace`` semantics — same-filesystem only. Use this
        for save-sort migrations inside the saves tree where source
        and destination are guaranteed to share a filesystem.
        """
        ...

    def getmtime(self, path: str) -> float:
        """Return the mtime of *path* as a Unix timestamp."""
        ...

    def walk_files(self, base_dir: str) -> list[tuple[str, list[str], list[str]]]:
        """Return ``os.walk``-style ``(dirpath, dirnames, filenames)`` triples for *base_dir*.

        Mirrors ``os.walk`` exactly: returns raw triples so callers
        retain control over directory pruning (e.g., skipping hidden
        directories).
        """
        ...


class RomFileAdapter(Protocol):
    """Filesystem seam for installed ROM file operations.

    Owns the raw POSIX calls RomRemovalService uses when physically
    removing an installed ROM (single file or multi-file ROM directory).
    Path-safety checks remain a domain concern (``domain.path_safety``);
    this Protocol exposes only the I/O seams.

    Implementations are synchronous — services that call from an async
    context offload via ``loop.run_in_executor``.
    """

    def is_dir(self, path: str) -> bool:
        """Return True when *path* exists and is a directory."""
        ...

    def exists(self, path: str) -> bool:
        """Return True when *path* refers to an existing file or directory."""
        ...

    def remove_file(self, path: str) -> None:
        """Delete *path*. Idempotent: a missing file is not an error."""
        ...

    def remove_tree(self, path: str) -> None:
        """Recursively delete *path* and all contents."""
        ...


class SaveFileAdapter(Protocol):
    """Filesystem seam for local save file operations.

    Owns the raw POSIX, ``open()``, ``tempfile``, and ``hashlib``-on-file
    calls SaveService and its sub-services use when reading, writing,
    backing up, hashing, and removing local save files under the
    RetroDECK saves directory. Path construction and platform-specific
    extension lookup remain a domain concern; this Protocol exposes only
    the I/O seams.

    Implementations are synchronous — services that call from an async
    context offload via ``loop.run_in_executor``.
    """

    def exists(self, path: str) -> bool:
        """Return True when *path* refers to an existing file or directory."""
        ...

    def is_file(self, path: str) -> bool:
        """Return True when *path* exists and is a regular file."""
        ...

    def is_dir(self, path: str) -> bool:
        """Return True when *path* exists and is a directory."""
        ...

    def make_dirs(self, path: str) -> None:
        """Create *path* and any missing parents. Idempotent."""
        ...

    def remove(self, path: str) -> None:
        """Delete *path*. Idempotent: a missing file is not an error."""
        ...

    def rename(self, src: str, dst: str) -> None:
        """Atomically rename *src* to *dst*, replacing any existing file at *dst*.

        Uses ``os.replace`` semantics — same-filesystem only.
        """
        ...

    def get_mtime(self, path: str) -> float:
        """Return the mtime of *path* as a Unix timestamp."""
        ...

    def get_size(self, path: str) -> int:
        """Return the size of *path* in bytes."""
        ...

    def checksum_md5(self, path: str) -> str:
        """Return the hex-encoded MD5 digest of *path*'s contents.

        Non-security use: drift detection between the local file and the
        recorded ``last_sync_hash`` baseline. A collision here would mean
        two different save files treated as identical — "sync misses an
        update", not a security breach.
        """
        ...

    def make_temp_path(self, suffix: str = "") -> str:
        """Return a fresh, unique path safe to write to.

        Backed by ``tempfile.mkstemp`` so the file is created atomically
        (``O_EXCL``) before the fd is closed. The caller owns the file
        and is responsible for removing it.
        """
        ...

    def read_bytes(self, path: str) -> bytes:
        """Return the contents of *path* as raw bytes."""
        ...

    def write_bytes(self, path: str, data: bytes) -> None:
        """Write *data* to *path*, overwriting any existing contents."""
        ...


class SgdbArtworkCache(Protocol):
    """Filesystem seam for the SteamGridDB artwork cache directory.

    Owns the raw POSIX calls SteamGridService uses to manage cached
    SGDB artwork (heroes, logos, grids, icons) under the plugin runtime
    directory. Path construction and pruning policy remain a service
    concern; this Protocol exposes only the I/O seams.

    Implementations are synchronous — services that call from an async
    context offload via ``loop.run_in_executor``.
    """

    def cache_dir(self) -> str:
        """Return the absolute path to the SGDB artwork cache directory.

        Idempotently ensures the directory exists before returning.
        """
        ...

    def exists(self, path: str) -> bool:
        """Return True when *path* refers to an existing file or directory."""
        ...

    def remove(self, path: str) -> None:
        """Delete *path*. Idempotent: a missing file is not an error."""
        ...

    def listdir(self, directory: str) -> list[str]:
        """Return the entries in *directory*."""
        ...

    def isdir(self, path: str) -> bool:
        """Return True when *path* exists and is a directory."""
        ...

    def read_bytes(self, path: str) -> bytes:
        """Return the contents of *path* as raw bytes."""
        ...

    def write_bytes_atomic(self, path: str, data: bytes) -> None:
        """Atomically write *data* to *path*.

        Writes to a temp file beside *path* and ``os.replace``s it to the
        final destination. The temp file is removed on any failure.
        """
        ...


# ---------------------------------------------------------------------------
# Multi-method cross-service Protocols
# ---------------------------------------------------------------------------


class RetryStrategy(Protocol):
    """HTTP retry wrapper pair consumed by SaveService and PlaytimeService."""

    def is_retryable(self, exc: Exception) -> bool: ...

    def with_retry(self, fn: Any, *args: Any, max_attempts: int = 3, base_delay: int = 1, **kwargs: Any) -> Any: ...


class BiosChecker(Protocol):
    """BIOS status checking consumed by GameDetailService."""

    def check_platform_bios_cached(self, platform_slug: str, rom_filename: str | None = None) -> dict | None: ...

    async def check_platform_bios(self, platform_slug: str, rom_filename: str | None = None) -> dict: ...


class AchievementsReader(Protocol):
    """Achievement data access consumed by GameDetailService."""

    def get_ra_username(self) -> str: ...

    def get_progress_cache_entry(self, rom_id_str: str) -> dict | None: ...


class MetadataExtractor(Protocol):
    """Metadata extraction and cache flushing consumed by LibraryService."""

    def extract_metadata(self, rom: dict) -> dict: ...

    def mark_metadata_dirty(self) -> None: ...

    def flush_metadata_if_dirty(self) -> None: ...


class ArtworkManager(Protocol):
    """Artwork operations consumed by LibraryService."""

    async def download_artwork(
        self,
        all_roms: list[dict],
        emit_progress: Any,
        is_cancelling: Any,
        progress_step: int = 4,
        progress_total_steps: int = 6,
    ) -> dict: ...

    def finalize_cover_path(self, grid: str | None, cover_path: str, app_id: int, rom_id_str: str) -> str: ...

    def remove_artwork_files(self, grid: str, rom_id: str | int, entry: dict) -> None: ...


class SteamGridDbApi(Protocol):
    """SteamGridDB HTTP API — search, artwork fetch, key verification."""

    def request(self, path: str) -> dict | None:
        """Authenticated GET to SGDB API v2. Returns parsed JSON or None if no API key."""
        ...

    def download_image(self, url: str, dest_path: str) -> bool:
        """Download image from URL to dest_path with atomic write. Returns True on success."""
        ...

    def verify_api_key(self, api_key: str) -> dict:
        """Verify an API key against SGDB. Returns parsed JSON response.

        Raises ``lib.errors.SgdbApiError`` on non-2xx HTTP responses
        (e.g. 401/403 for an invalid key).
        """
        ...
